[package]
name = "nexa-root-map-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
nexa-bytecode = { path = "../../crates/nexa-bytecode" }
nexa-verifier = { path = "../../crates/nexa-verifier" }

[[bin]]
name = "root_map"
path = "fuzz_targets/root_map.rs"
test = false
doc = false
bench = false
