[package]
name = "nexa"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nexa-analysis = { path = "../nexa-analysis" }
nexa-bytecode = { path = "../nexa-bytecode" }
nexa-compiler = { path = "../nexa-compiler" }
nexa-core = { path = "../nexa-core" }
nexa-diagnostics = { path = "../nexa-diagnostics" }
nexa-idl = { path = "../nexa-idl" }
nexa-runtime = { path = "../nexa-runtime", features = ["model-adapter"] }
nexa-stdlib = { path = "../nexa-stdlib" }
nexa-syntax = { path = "../nexa-syntax" }
nexa-test-runner = { path = "../nexa-test-runner" }
nexa-verifier = { path = "../nexa-verifier" }
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
