system RealmRuntime
max_depth 8
max_requests 1
max_tokens 1

component HostRequest
component ResourceToken
component Reload
component ModuleEpochRoot
component OldTask
component ReleaseQueue

invariant reservations_match_live_resources
invariant completed_resources_have_release_records
invariant reload_has_single_staging_graph
invariant publication_switches_active_epoch_once
invariant publication_cancels_old_tasks
invariant activation_failure_keeps_candidate_root
invariant activation_failure_never_restores_old_execution

end
