[package]
name = "nexa-idl"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
blake3.workspace = true
nexa-bytecode = { path = "../nexa-bytecode" }
nexa-core = { path = "../nexa-core" }
nexa-syntax = { path = "../nexa-syntax" }
prettyplease = "0.2"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[dev-dependencies]
nexa-compiler = { path = "../nexa-compiler" }
nexa-runtime = { path = "../nexa-runtime", features = ["model-adapter"] }
nexa-verifier = { path = "../nexa-verifier" }
serde_json.workspace = true

[lints]
workspace = true
