[package]
name = "nexa-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nexa = { path = "../nexa" }
nexa-bytecode = { path = "../nexa-bytecode" }
nexa-compiler = { path = "../nexa-compiler" }
nexa-core = { path = "../nexa-core" }
nexa-idl = { path = "../nexa-idl" }
nexa-machine = { path = "../nexa-machine" }
nexa-migrate = { path = "../nexa-migrate" }
nexa-model = { path = "../nexa-model" }
nexa-runtime = { path = "../nexa-runtime" }
nexa-verifier = { path = "../nexa-verifier" }
serde_json.workspace = true

[lints]
workspace = true

[[bin]]
name = "nexa"
path = "src/main.rs"
