[package]
name = "nexa-model"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nexa-core = { path = "../nexa-core" }
nexa-machine = { path = "../nexa-machine" }

[dev-dependencies]
nexa-bytecode = { path = "../nexa-bytecode" }
nexa-runtime = { path = "../nexa-runtime", features = ["model-adapter"] }
nexa-verifier = { path = "../nexa-verifier" }

[lints]
workspace = true
