use nexa_idl::{
    BindingModel, CodegenError, abi_descriptor, contract_fingerprint, generate_rust,
    generate_rust_tokens, parse,
};

const CODEGEN_CONTRACT: &str = r"
contract Bindings {
    handle Entity;

    struct Position {
        x: f32,
        y: f32,
    }

    enum Event {
        Idle,
        Moved(Position),
        Cancelled,
    }

    host {
        fn format_event(event: Event) -> string;

        @cancel(return_error)
        @abandon(trap)
        async fn load(entity: Entity) -> Result<Position, Event>;

        fn token(entity: Entity) -> Token<Entity>;
        fn snapshot() -> Snapshot<Position>;
    }

    nexa {
        fn on_event(entity: Entity, event: Event) -> Option<Position>;
        async fn refresh(entity: Entity) -> Result<Position, Event>;
    }
}
";

#[test]
fn binding_model_contains_prevalidated_names_and_strategies() {
    let contract = parse(CODEGEN_CONTRACT).unwrap();
    let model = BindingModel::from_contract(&contract).unwrap();
    assert_eq!(model.identity.source_name, "Bindings");
    assert_eq!(model.host_trait_ident.to_string(), "BindingsHost");
    assert_eq!(model.handles[0].identity.rust_ident.to_string(), "Entity");
    let on_event = model
        .nexa_functions
        .iter()
        .find(|function| function.identity.source_name == "on_event")
        .unwrap();
    assert_eq!(on_event.marker_ident.to_string(), "OnEvent");
    assert_eq!(on_event.args_ident.to_string(), "OnEventArgs");
    assert_eq!(on_event.output_ident.to_string(), "OnEventOutput");

    let load = model
        .host_functions
        .iter()
        .find(|function| function.identity.source_name == "load")
        .unwrap();
    let host_contract = load.host_contract.as_ref().unwrap();
    assert_eq!(host_contract.mode, nexa_bytecode::HostCallMode::Async);
    assert_eq!(host_contract.parameters.len(), 1);
    assert!(host_contract.result.is_some());
    let async_result = host_contract.async_result.unwrap();
    assert_eq!(async_result.cancel_error, Some(2));
    assert_eq!(async_result.abandon_error, None);
    assert_ne!(load.declaration_fingerprint, [0; 32]);
}

#[test]
fn generated_tokens_are_parsed_formatted_and_parsed_again() {
    let contract = parse(CODEGEN_CONTRACT).unwrap();
    let tokens = generate_rust_tokens(&contract).unwrap();
    syn::parse2::<syn::File>(tokens).unwrap();

    let source = generate_rust(&contract).unwrap();
    syn::parse_file(&source).unwrap();
    assert!(source.starts_with("// @generated by nexa-idl v2. DO NOT EDIT.\n"));
    for required in [
        "pub const CONTRACT_FINGERPRINT",
        "pub const CONTRACT_RUNTIME_ID",
        "pub const CONTRACT_SOURCE_NAME",
        "pub const NIDL_SYNTAX_VERSION: u16 = 2",
        "pub const HOST_CONTRACT_SCHEMA_VERSION: u32 = 2",
        "pub const ABI_DESCRIPTOR_VERSION: u16 = 2",
        "pub trait BindingsHost",
        "pub struct GeneratedHostRegistry",
        "pub static HOST_FUNCTION_AUTHORITIES",
        "::std::sync::LazyLock",
        "nexa_runtime::HostFunctionAuthority::new",
        "fn resolve_function(",
        "nexa_runtime::HostFunctionSlot::new",
        "match slot.index()",
        "pub struct Entity",
        "pub struct EntityToken",
        "pub struct PositionSnapshot",
        "pub struct LoadCompletionTicket",
        "pub enum OnEvent",
        "pub struct OnEventArgs",
        "pub type OnEventOutput",
        "const NAME: &'static str = \"on_event\"",
        "fn effect() -> nexa_runtime::FunctionEffect",
        "nexa_runtime::FunctionEffect::Ordinary",
        "nexa_runtime::FunctionEffect::Task",
    ] {
        assert!(source.contains(required), "missing `{required}`:\n{source}");
    }
    for removed in [
        "LEGACY_FUNCTION_INDEX",
        "INTERFACE_HASH",
        "EXPORT_NAME",
        "EXPORT_ID",
    ] {
        assert!(!source.contains(removed), "legacy output `{removed}`");
    }
}

#[test]
fn generated_registry_resolves_stable_ids_to_dense_slots() {
    let contract = parse(
        "contract Dispatch { host { \
         fn first() -> i32; \
         fn second() -> i32; \
         fn third() -> i32; \
         } }",
    )
    .unwrap();
    let model = BindingModel::from_contract(&contract).unwrap();
    let third = model
        .host_functions
        .iter()
        .find(|function| function.identity.source_name == "third")
        .unwrap();
    let source = generate_rust(&contract).unwrap();

    assert!(source.contains("id: nexa_runtime::StableId"));
    assert!(
        source.contains(&format!(
            "nexa_runtime::StableId({}u64) =>",
            third.identity.stable_id.0
        )),
        "third Host function is not resolved by its stable identity:\n{source}"
    );
    assert!(
        source.contains("nexa_runtime::HostFunctionSlot::new(2u32)"),
        "third Host function did not resolve to dense slot 2:\n{source}"
    );
    assert!(source.contains("match slot.index()"));
}

#[test]
fn illegal_or_colliding_names_never_reach_executable_rust() {
    for source in [
        "contract Self {}",
        "contract Inject { struct GeneratedHostRegistry {} }",
        "contract Collision { nexa { fn on_event(); fn on__event(); } }",
        "contract Inject { nexa { fn r#break(); } }",
    ] {
        match parse(source) {
            Err(_) => {}
            Ok(contract) => {
                assert!(
                    matches!(
                        generate_rust_tokens(&contract),
                        Err(CodegenError::InvalidRustIdentifier { .. }
                            | CodegenError::RustNameCollision { .. })
                    ),
                    "unsafe generated name reached TokenStream: {source}"
                );
            }
        }
    }
}

#[test]
fn codegen_descriptor_and_fingerprint_are_byte_deterministic() {
    let contract = parse(CODEGEN_CONTRACT).unwrap();
    let first_source = generate_rust(&contract).unwrap();
    let first_descriptor = abi_descriptor(&contract);
    let first_fingerprint = contract_fingerprint(&contract);
    for _ in 0..10 {
        assert_eq!(generate_rust(&contract).unwrap(), first_source);
        assert_eq!(abi_descriptor(&contract).bytes, first_descriptor.bytes);
        assert_eq!(contract_fingerprint(&contract), first_fingerprint);
    }
}

#[test]
fn recursive_collection_layouts_stop_at_generated_named_codec_boundaries() {
    let contract = parse(
        r"
        contract RecursiveBindings {
            enum Tree {
                Leaf(i32),
                Children(Array<Tree>),
            }

            struct Node {
                children: Array<Node>,
            }

            host {
                fn inspect(tree: Tree) -> Tree;
                fn snapshot() -> Snapshot<Node>;
            }

            nexa {
                fn build(tree: Tree) -> Tree;
            }
        }
        ",
    )
    .unwrap();
    let source = generate_rust(&contract).unwrap();
    syn::parse_file(&source).unwrap();
    for helper in [
        "__nexa_requirements",
        "__nexa_encode_runtime",
        "__nexa_completion_payload",
        "__nexa_decode_script",
        "__nexa_snapshot_encode",
        "__nexa_snapshot_decode",
    ] {
        assert!(
            source.contains(helper),
            "missing recursive boundary `{helper}`"
        );
    }
}

#[test]
fn host_collections_are_typed_views_and_prelude_types_are_qualified() {
    let contract = parse(
        r"
        contract TypedCollections {
            handle Some;
            handle Box;
            handle None;
            handle Ok;
            handle Err;
            handle TryFrom;
            handle From;

            struct String {
                value: string,
            }

            struct Vec {
                value: string,
            }

            enum Error {
                Cancelled,
                Abandoned,
            }

            host {
                fn consume(
                    values: Array<String>,
                    bytes: Buffer<Option<Vec>>,
                );
                fn token() -> Token<Some>;
                fn compact() -> Buffer<Option<Vec>>;
                fn structs() -> Array<Vec>;
                async fn load(values: Array<String>) -> Result<Vec, Error>;
            }
        }
        ",
    )
    .unwrap();
    let source = generate_rust(&contract).unwrap();
    syn::parse_file(&source).unwrap();
    assert!(source.contains("__NexaArrayRef<'a, StringRef<'a>>"));
    assert!(source.contains("__NexaBufferRef<'a, ::std::option::Option<VecRef<'a>>>"));
    assert!(source.contains("::std::string::String"));
    assert!(source.contains("::std::boxed::Box"));
    assert!(
        source.contains("begin_reference_buffer"),
        "Buffer<Option<T>> must select compact named-reference storage"
    );
    assert!(
        source.contains("begin_array"),
        "Array<Struct> must retain value/row storage"
    );
    assert!(!source.contains("values: nexa_runtime::HostArrayRef"));
    assert!(!source.contains("bytes: nexa_runtime::HostBufferRef"));
}

#[test]
fn snapshot_schema_tracks_the_transitive_type_layout() {
    let first = parse(
        "contract SnapshotContract { \
         struct Inner { value: i32, } \
         struct Outer { inner: Inner, } \
         host { fn snapshot() -> Snapshot<Outer>; } }",
    )
    .unwrap();
    let changed = parse(
        "contract SnapshotContract { \
         struct Inner { value: i32, enabled: bool, } \
         struct Outer { inner: Inner, } \
         host { fn snapshot() -> Snapshot<Outer>; } }",
    )
    .unwrap();
    let schema = |contract| {
        BindingModel::from_contract(contract)
            .unwrap()
            .structs
            .into_iter()
            .find(|structure| structure.identity.source_name == "Outer")
            .unwrap()
            .snapshot_schema_id
    };
    assert_ne!(schema(&first), schema(&changed));
}

#[test]
fn binding_model_rejects_unencodable_snapshot_contents() {
    for source in [
        "contract SnapshotContract { \
         handle Entity; \
         struct Bad { entity: Entity, } \
         host { fn snapshot() -> Snapshot<Bad>; } }",
        "contract SnapshotContract { \
         handle Entity; \
         struct Bad { token: Token<Entity>, } \
         host { fn snapshot() -> Snapshot<Bad>; } }",
        "contract SnapshotContract { \
         struct Inner { value: i32, } \
         struct Bad { nested: Snapshot<Inner>, } \
         host { fn snapshot() -> Snapshot<Bad>; } }",
    ] {
        let contract = parse(source).unwrap();
        assert!(
            matches!(
                BindingModel::from_contract(&contract),
                Err(CodegenError::UnsupportedSnapshotContent { .. })
            ),
            "unsupported snapshot content reached code generation: {source}"
        );
    }
}

#[test]
#[ignore = "spawns a nested Cargo check; exercised by the structured-codegen gate"]
fn generated_fixture_cargo_checks() {
    let contract = parse(CODEGEN_CONTRACT).unwrap();
    let generated = generate_rust(&contract).unwrap();
    let nonce = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let directory =
        std::env::temp_dir().join(format!("nexa-codegen-v2-{}-{nonce}", std::process::id()));
    std::fs::create_dir_all(directory.join("src")).unwrap();
    let runtime = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../nexa-runtime")
        .canonicalize()
        .unwrap();
    std::fs::write(
        directory.join("Cargo.toml"),
        format!(
            "[package]\nname=\"nexa-codegen-v2-check\"\nversion=\"0.0.0\"\nedition=\"2024\"\n\
             [dependencies]\nnexa-runtime={{path={runtime:?}}}\n"
        ),
    )
    .unwrap();
    std::fs::write(directory.join("src/lib.rs"), generated).unwrap();
    let output = std::process::Command::new("cargo")
        .args(["check", "--quiet"])
        .current_dir(&directory)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "generated fixture failed:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
    std::fs::remove_dir_all(directory).unwrap();
}
