# Nexa internal-language task lifecycle.
machine Task

state Created initial
state Ready
state Running
state FuelYielded
state ExplicitYielded
state Waiting
state CancelRequested
state Cancelling
state Cleanup
state Completed terminal
state Cancelled terminal
state Trapped terminal

event Admit
event Poll
event YieldFuel
event YieldExplicit
event AwaitHost
event Resume
event ResumeExplicit
event ReachSafepoint
event RequestCancel
event BeginCleanup
event Clean
event Finish
event Trap

guard owner_scope_valid
guard continuation_reserved

resource task_slot

invariant nonnegative task_slot
invariant terminal_zero task_slot
invariant state_requires Running task_slot 1

transition TASK_CREATED_ADMIT_READY Created Admit Ready when=owner_scope_valid when=continuation_reserved delta=task_slot:+1
transition TASK_READY_POLL_RUNNING Ready Poll Running
transition TASK_FUEL_YIELDED_RESUME_RUNNING FuelYielded Resume Running
transition TASK_RUNNING_FUEL_YIELDED Running YieldFuel FuelYielded
transition TASK_EXPLICIT_YIELDED_RESUME_RUNNING ExplicitYielded ResumeExplicit Running
transition TASK_RUNNING_EXPLICIT_YIELDED Running YieldExplicit ExplicitYielded
transition TASK_RUNNING_AWAIT_WAITING Running AwaitHost Waiting
transition TASK_WAITING_RESUME_RUNNING Waiting Resume Running
transition TASK_RUNNING_CANCEL_REQUESTED Running RequestCancel CancelRequested
transition TASK_WAITING_CANCEL_REQUESTED Waiting RequestCancel CancelRequested
transition TASK_FUEL_YIELDED_CANCEL_REQUESTED FuelYielded RequestCancel CancelRequested
transition TASK_EXPLICIT_YIELDED_CANCEL_REQUESTED ExplicitYielded RequestCancel CancelRequested
transition TASK_CANCEL_REQUEST_REACH_CANCELLING CancelRequested ReachSafepoint Cancelling
transition TASK_CANCELLING_BEGIN_CLEANUP Cancelling BeginCleanup Cleanup
transition TASK_CANCELLING_CLEAN_CANCELLED Cancelling Clean Cancelled delta=task_slot:-1
transition TASK_CLEANUP_CLEAN_CANCELLED Cleanup Clean Cancelled delta=task_slot:-1
transition TASK_RUNNING_FINISH_COMPLETED Running Finish Completed delta=task_slot:-1
transition TASK_RUNNING_TRAP_TRAPPED Running Trap Trapped delta=task_slot:-1
transition TASK_CANCELLING_TRAP_TRAPPED Cancelling Trap Trapped delta=task_slot:-1
transition TASK_CLEANUP_TRAP_TRAPPED Cleanup Trap Trapped delta=task_slot:-1

end
