//! Exact-build IDL parsing, canonical hashing and Rust binding generation.

use std::fmt;
use std::fmt::Write;

use nexa_core::StableId;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Idl {
    pub interface: String,
    pub opaque_handles: Vec<String>,
    pub structs: Vec<Struct>,
    pub functions: Vec<HostFunction>,
    pub exports: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Struct {
    pub name: String,
    pub fields: Vec<Field>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Field {
    pub name: String,
    pub ty: TypeRef,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HostFunction {
    pub name: String,
    pub parameters: Vec<Field>,
    pub result: TypeRef,
    pub synchronous: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TypeRef {
    I32,
    F32,
    Bool,
    String,
    HostRequest,
    ResourceToken,
    Snapshot,
    Named(String),
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum IdlError {
    MissingInterface,
    Syntax(String),
    Duplicate(String),
    UnknownType(String),
}

impl fmt::Display for IdlError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{self:?}")
    }
}

impl std::error::Error for IdlError {}

pub fn parse(source: &str) -> Result<Idl, IdlError> {
    let cleaned = source
        .lines()
        .map(|line| line.split("//").next().unwrap_or_default())
        .collect::<Vec<_>>()
        .join(" ");
    let tokens = tokenize(&cleaned);
    let mut parser = Parser { tokens, cursor: 0 };
    parser.parse()
}

#[must_use]
pub fn exact_hash(idl: &Idl) -> StableId {
    StableId::from_name(&canonical(idl))
}

#[must_use]
pub fn canonical(idl: &Idl) -> String {
    let mut output = format!("interface:{};", idl.interface);
    for handle in &idl.opaque_handles {
        write!(output, "opaque:{handle};").expect("String writes do not fail");
    }
    for structure in &idl.structs {
        write!(output, "struct:{}{{", structure.name).expect("String writes do not fail");
        for field in &structure.fields {
            write!(output, "{}:{};", field.name, type_name(&field.ty))
                .expect("String writes do not fail");
        }
        output.push('}');
    }
    for function in &idl.functions {
        write!(
            output,
            "fn:{}:{}(",
            if function.synchronous {
                "sync"
            } else {
                "request"
            },
            function.name
        )
        .expect("String writes do not fail");
        for parameter in &function.parameters {
            write!(output, "{}:{};", parameter.name, type_name(&parameter.ty))
                .expect("String writes do not fail");
        }
        write!(output, ")->{};", type_name(&function.result)).expect("String writes do not fail");
    }
    for export in &idl.exports {
        write!(output, "export:{export};").expect("String writes do not fail");
    }
    output
}

#[must_use]
pub fn generate_rust(idl: &Idl) -> String {
    let mut output = String::from(
        "// @generated by nexa-idl; do not edit.\n\
         pub struct HostCallContext<'a> { pub realm: &'a mut dyn core::any::Any }\n\
         #[derive(Debug)] pub struct HostError;\n",
    );
    for handle in &idl.opaque_handles {
        writeln!(
            output,
            "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)] pub struct {handle}(pub u64);"
        )
        .expect("String writes do not fail");
    }
    for structure in &idl.structs {
        writeln!(
            output,
            "#[derive(Clone, Debug, PartialEq)] pub struct {} {{",
            structure.name
        )
        .expect("String writes do not fail");
        for field in &structure.fields {
            writeln!(output, "    pub {}: {},", field.name, rust_type(&field.ty))
                .expect("String writes do not fail");
        }
        output.push_str("}\n");
    }
    writeln!(output, "pub trait {} {{", idl.interface).expect("String writes do not fail");
    for function in &idl.functions {
        write!(
            output,
            "    fn {}(&mut self, context: &mut HostCallContext<'_>",
            function.name
        )
        .expect("String writes do not fail");
        for parameter in &function.parameters {
            write!(output, ", {}: {}", parameter.name, rust_type(&parameter.ty))
                .expect("String writes do not fail");
        }
        writeln!(
            output,
            ") -> Result<{}, HostError>;",
            rust_type(&function.result)
        )
        .expect("String writes do not fail");
    }
    output.push_str("}\n");
    for (index, function) in idl.functions.iter().enumerate() {
        writeln!(
            output,
            "pub const THUNK_{}: u32 = {index};",
            function.name.to_ascii_uppercase()
        )
        .expect("String writes do not fail");
    }
    for export in &idl.exports {
        writeln!(
            output,
            "pub enum {export} {{}} impl {export} {{ pub const EXPORT_NAME: &'static str = \"{export}\"; }}"
        )
        .expect("String writes do not fail");
    }
    output
}

fn type_name(ty: &TypeRef) -> &str {
    match ty {
        TypeRef::I32 => "i32",
        TypeRef::F32 => "f32",
        TypeRef::Bool => "bool",
        TypeRef::String => "string",
        TypeRef::HostRequest => "host_request",
        TypeRef::ResourceToken => "resource_token",
        TypeRef::Snapshot => "snapshot",
        TypeRef::Named(name) => name,
    }
}

fn rust_type(ty: &TypeRef) -> &str {
    match ty {
        TypeRef::I32 => "i32",
        TypeRef::F32 => "f32",
        TypeRef::Bool => "bool",
        TypeRef::String => "String",
        TypeRef::HostRequest => "nexa_runtime::HostRequestHandle",
        TypeRef::ResourceToken => "nexa_runtime::ResourceTokenHandle",
        TypeRef::Snapshot => "nexa_runtime::ImmutableSnapshot<i32>",
        TypeRef::Named(name) => name,
    }
}

fn tokenize(source: &str) -> Vec<String> {
    let mut output = String::new();
    for character in source.chars() {
        if "{}(),:;".contains(character) {
            output.push(' ');
            output.push(character);
            output.push(' ');
        } else if character == '-' {
            output.push(' ');
            output.push(character);
        } else if character == '>' {
            output.push(character);
            output.push(' ');
        } else {
            output.push(character);
        }
    }
    output.split_whitespace().map(str::to_owned).collect()
}

struct Parser {
    tokens: Vec<String>,
    cursor: usize,
}

impl Parser {
    fn parse(&mut self) -> Result<Idl, IdlError> {
        self.expect("interface")?;
        let interface = self.word()?;
        self.expect("{")?;
        let mut idl = Idl {
            interface,
            opaque_handles: Vec::new(),
            structs: Vec::new(),
            functions: Vec::new(),
            exports: Vec::new(),
        };
        while !self.take("}") {
            match self.peek() {
                Some("opaque") => {
                    self.cursor += 1;
                    let name = self.word()?;
                    self.expect(";")?;
                    insert_unique(&mut idl.opaque_handles, name)?;
                }
                Some("struct") => {
                    self.cursor += 1;
                    let name = self.word()?;
                    self.expect("{")?;
                    let mut fields = Vec::new();
                    while !self.take("}") {
                        fields.push(self.field()?);
                        self.expect(";")?;
                    }
                    if idl.structs.iter().any(|item| item.name == name) {
                        return Err(IdlError::Duplicate(name));
                    }
                    idl.structs.push(Struct { name, fields });
                }
                Some("sync" | "request") => {
                    let synchronous = self.word()? == "sync";
                    self.expect("fn")?;
                    let name = self.word()?;
                    self.expect("(")?;
                    let mut parameters = Vec::new();
                    if !self.take(")") {
                        loop {
                            parameters.push(self.field()?);
                            if self.take(")") {
                                break;
                            }
                            self.expect(",")?;
                        }
                    }
                    self.expect("->")?;
                    let result = self.ty()?;
                    self.expect(";")?;
                    if idl.functions.iter().any(|item| item.name == name) {
                        return Err(IdlError::Duplicate(name));
                    }
                    idl.functions.push(HostFunction {
                        name,
                        parameters,
                        result,
                        synchronous,
                    });
                }
                Some("export") => {
                    self.cursor += 1;
                    let name = self.word()?;
                    self.expect(";")?;
                    insert_unique(&mut idl.exports, name)?;
                }
                token => return Err(IdlError::Syntax(format!("unexpected {token:?}"))),
            }
        }
        validate_types(&idl)?;
        Ok(idl)
    }

    fn field(&mut self) -> Result<Field, IdlError> {
        let name = self.word()?;
        self.expect(":")?;
        Ok(Field {
            name,
            ty: self.ty()?,
        })
    }

    fn ty(&mut self) -> Result<TypeRef, IdlError> {
        Ok(match self.word()?.as_str() {
            "i32" => TypeRef::I32,
            "f32" => TypeRef::F32,
            "bool" => TypeRef::Bool,
            "string" => TypeRef::String,
            "host_request" => TypeRef::HostRequest,
            "resource_token" => TypeRef::ResourceToken,
            "snapshot" => TypeRef::Snapshot,
            named => TypeRef::Named(named.to_owned()),
        })
    }

    fn peek(&self) -> Option<&str> {
        self.tokens.get(self.cursor).map(String::as_str)
    }

    fn take(&mut self, token: &str) -> bool {
        if self.peek() == Some(token) {
            self.cursor += 1;
            true
        } else {
            false
        }
    }

    fn expect(&mut self, token: &str) -> Result<(), IdlError> {
        if self.take(token) {
            Ok(())
        } else {
            Err(IdlError::Syntax(format!(
                "expected `{token}`, found {:?}",
                self.peek()
            )))
        }
    }

    fn word(&mut self) -> Result<String, IdlError> {
        let word = self
            .tokens
            .get(self.cursor)
            .ok_or_else(|| IdlError::Syntax("unexpected end".into()))?
            .clone();
        self.cursor += 1;
        Ok(word)
    }
}

fn insert_unique(items: &mut Vec<String>, name: String) -> Result<(), IdlError> {
    if items.contains(&name) {
        Err(IdlError::Duplicate(name))
    } else {
        items.push(name);
        Ok(())
    }
}

fn validate_types(idl: &Idl) -> Result<(), IdlError> {
    let known = |name: &str| {
        idl.opaque_handles.iter().any(|item| item == name)
            || idl.structs.iter().any(|item| item.name == name)
    };
    for ty in idl
        .structs
        .iter()
        .flat_map(|structure| structure.fields.iter().map(|field| &field.ty))
        .chain(idl.functions.iter().flat_map(|function| {
            function
                .parameters
                .iter()
                .map(|field| &field.ty)
                .chain(std::iter::once(&function.result))
        }))
    {
        if let TypeRef::Named(name) = ty
            && !known(name)
        {
            return Err(IdlError::UnknownType(name.clone()));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{exact_hash, generate_rust, parse};

    const IDL: &str = "
        interface GameHost {
            opaque Entity;
            struct Vec3 { x: f32; y: f32; z: f32; }
            sync fn entity_position(entity: Entity) -> Vec3;
            export Update;
        }
    ";

    #[test]
    fn exact_hash_ignores_comments_and_whitespace_but_preserves_field_order() {
        let first = parse(IDL).unwrap();
        let second = parse(&format!("// comment\n{IDL}")).unwrap();
        assert_eq!(exact_hash(&first), exact_hash(&second));
        let reordered = parse(&IDL.replace("x: f32; y: f32", "y: f32; x: f32")).unwrap();
        assert_ne!(exact_hash(&first), exact_hash(&reordered));
    }

    #[test]
    fn binding_has_typed_trait_thunk_and_export_marker() {
        let generated = generate_rust(&parse(IDL).unwrap());
        assert!(generated.contains("pub trait GameHost"));
        assert!(generated.contains("entity_position"));
        assert!(generated.contains("THUNK_ENTITY_POSITION"));
        assert!(generated.contains("pub enum Update"));
    }
}
