[package]
name = "combat-runtime"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
nexa = { path = "../../crates/nexa" }
nexa-bytecode = { path = "../../crates/nexa-bytecode" }
nexa-core = { path = "../../crates/nexa-core" }
nexa-embed = { path = "../../crates/nexa-embed" }
nexa-contract = { path = "../../crates/nexa-contract" }
nexa-runtime = { path = "../../crates/nexa-runtime" }

[build-dependencies]
nexa-contract = { path = "../../crates/nexa-contract" }
