[package]
name = "combat-runtime"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
nexa-compiler = { path = "../../crates/nexa-compiler" }
nexa-core = { path = "../../crates/nexa-core" }
nexa-idl = { path = "../../crates/nexa-idl" }
nexa-runtime = { path = "../../crates/nexa-runtime" }

[build-dependencies]
nexa-idl = { path = "../../crates/nexa-idl" }
