[package]
name = "nexa-allocation-observer"
version = "0.1.0"
edition = "2024"
publish = false
build = "build.rs"

[dependencies]
nexa-bytecode = { path = "../../crates/nexa-bytecode" }
nexa-core = { path = "../../crates/nexa-core" }
nexa-runtime = { path = "../../crates/nexa-runtime" }
nexa-verifier = { path = "../../crates/nexa-verifier" }

[build-dependencies]
nexa-idl = { path = "../../crates/nexa-idl" }

[lints.rust]
unsafe_code = "allow"
