/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 102
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 68
#define ALIAS_COUNT 0
#define TOKEN_COUNT 41
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 12
#define SUPERTYPE_COUNT 2

enum ts_symbol_identifiers {
  sym_nidl_identifier = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_SEMI = 4,
  anon_sym_COLON = 5,
  anon_sym_COMMA = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LT = 9,
  anon_sym_GT = 10,
  sym_interface_keyword = 11,
  sym_opaque_keyword = 12,
  sym_nidl_struct_keyword = 13,
  sym_nidl_enum_keyword = 14,
  sym_nidl_function_keyword = 15,
  sym_export_keyword = 16,
  anon_sym_sync = 17,
  anon_sym_request = 18,
  sym_fuel_keyword = 19,
  anon_sym_return_error = 20,
  anon_sym_cancel_task = 21,
  anon_sym_trap = 22,
  anon_sym_i32 = 23,
  anon_sym_i64 = 24,
  anon_sym_f32 = 25,
  anon_sym_f64 = 26,
  anon_sym_bool = 27,
  anon_sym_rune = 28,
  anon_sym_string = 29,
  anon_sym_host_request = 30,
  anon_sym_resource_token = 31,
  anon_sym_token = 32,
  anon_sym_snapshot = 33,
  anon_sym_array = 34,
  anon_sym_buffer = 35,
  anon_sym_Option = 36,
  anon_sym_Result = 37,
  sym_void_type = 38,
  sym_integer_literal = 39,
  sym_return_arrow_operator = 40,
  sym_source_file = 41,
  sym_nidl_document = 42,
  sym_nidl_member = 43,
  sym_opaque_declaration = 44,
  sym_nidl_struct_declaration = 45,
  sym_nidl_field_declaration = 46,
  sym_nidl_enum_declaration = 47,
  sym_nidl_enum_variant = 48,
  sym_host_function_declaration = 49,
  sym_request_policy = 50,
  sym_fuel_clause = 51,
  sym_nidl_parameter_list = 52,
  sym_nidl_parameter = 53,
  sym_export_declaration = 54,
  sym_nidl_type = 55,
  sym_nidl_generic_type = 56,
  sym_nidl_type_argument_list = 57,
  sym_nidl_type_identifier = 58,
  sym_host_mode_keyword = 59,
  sym_cancel_policy_keyword = 60,
  sym_abandon_policy_keyword = 61,
  sym_nidl_builtin_type = 62,
  aux_sym_nidl_document_repeat1 = 63,
  aux_sym_nidl_struct_declaration_repeat1 = 64,
  aux_sym_nidl_enum_declaration_repeat1 = 65,
  aux_sym_nidl_parameter_list_repeat1 = 66,
  aux_sym_nidl_type_argument_list_repeat1 = 67,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_nidl_identifier] = "nidl_identifier",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym_interface_keyword] = "interface_keyword",
  [sym_opaque_keyword] = "opaque_keyword",
  [sym_nidl_struct_keyword] = "nidl_struct_keyword",
  [sym_nidl_enum_keyword] = "nidl_enum_keyword",
  [sym_nidl_function_keyword] = "nidl_function_keyword",
  [sym_export_keyword] = "export_keyword",
  [anon_sym_sync] = "sync",
  [anon_sym_request] = "request",
  [sym_fuel_keyword] = "fuel_keyword",
  [anon_sym_return_error] = "return_error",
  [anon_sym_cancel_task] = "cancel_task",
  [anon_sym_trap] = "trap",
  [anon_sym_i32] = "i32",
  [anon_sym_i64] = "i64",
  [anon_sym_f32] = "f32",
  [anon_sym_f64] = "f64",
  [anon_sym_bool] = "bool",
  [anon_sym_rune] = "rune",
  [anon_sym_string] = "string",
  [anon_sym_host_request] = "host_request",
  [anon_sym_resource_token] = "resource_token",
  [anon_sym_token] = "token",
  [anon_sym_snapshot] = "snapshot",
  [anon_sym_array] = "array",
  [anon_sym_buffer] = "buffer",
  [anon_sym_Option] = "Option",
  [anon_sym_Result] = "Result",
  [sym_void_type] = "void_type",
  [sym_integer_literal] = "integer_literal",
  [sym_return_arrow_operator] = "return_arrow_operator",
  [sym_source_file] = "source_file",
  [sym_nidl_document] = "nidl_document",
  [sym_nidl_member] = "nidl_member",
  [sym_opaque_declaration] = "opaque_declaration",
  [sym_nidl_struct_declaration] = "nidl_struct_declaration",
  [sym_nidl_field_declaration] = "nidl_field_declaration",
  [sym_nidl_enum_declaration] = "nidl_enum_declaration",
  [sym_nidl_enum_variant] = "nidl_enum_variant",
  [sym_host_function_declaration] = "host_function_declaration",
  [sym_request_policy] = "request_policy",
  [sym_fuel_clause] = "fuel_clause",
  [sym_nidl_parameter_list] = "nidl_parameter_list",
  [sym_nidl_parameter] = "nidl_parameter",
  [sym_export_declaration] = "export_declaration",
  [sym_nidl_type] = "nidl_type",
  [sym_nidl_generic_type] = "nidl_generic_type",
  [sym_nidl_type_argument_list] = "nidl_type_argument_list",
  [sym_nidl_type_identifier] = "nidl_type_identifier",
  [sym_host_mode_keyword] = "host_mode_keyword",
  [sym_cancel_policy_keyword] = "cancel_policy_keyword",
  [sym_abandon_policy_keyword] = "abandon_policy_keyword",
  [sym_nidl_builtin_type] = "nidl_builtin_type",
  [aux_sym_nidl_document_repeat1] = "nidl_document_repeat1",
  [aux_sym_nidl_struct_declaration_repeat1] = "nidl_struct_declaration_repeat1",
  [aux_sym_nidl_enum_declaration_repeat1] = "nidl_enum_declaration_repeat1",
  [aux_sym_nidl_parameter_list_repeat1] = "nidl_parameter_list_repeat1",
  [aux_sym_nidl_type_argument_list_repeat1] = "nidl_type_argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_nidl_identifier] = sym_nidl_identifier,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym_interface_keyword] = sym_interface_keyword,
  [sym_opaque_keyword] = sym_opaque_keyword,
  [sym_nidl_struct_keyword] = sym_nidl_struct_keyword,
  [sym_nidl_enum_keyword] = sym_nidl_enum_keyword,
  [sym_nidl_function_keyword] = sym_nidl_function_keyword,
  [sym_export_keyword] = sym_export_keyword,
  [anon_sym_sync] = anon_sym_sync,
  [anon_sym_request] = anon_sym_request,
  [sym_fuel_keyword] = sym_fuel_keyword,
  [anon_sym_return_error] = anon_sym_return_error,
  [anon_sym_cancel_task] = anon_sym_cancel_task,
  [anon_sym_trap] = anon_sym_trap,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_i64] = anon_sym_i64,
  [anon_sym_f32] = anon_sym_f32,
  [anon_sym_f64] = anon_sym_f64,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_rune] = anon_sym_rune,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_host_request] = anon_sym_host_request,
  [anon_sym_resource_token] = anon_sym_resource_token,
  [anon_sym_token] = anon_sym_token,
  [anon_sym_snapshot] = anon_sym_snapshot,
  [anon_sym_array] = anon_sym_array,
  [anon_sym_buffer] = anon_sym_buffer,
  [anon_sym_Option] = anon_sym_Option,
  [anon_sym_Result] = anon_sym_Result,
  [sym_void_type] = sym_void_type,
  [sym_integer_literal] = sym_integer_literal,
  [sym_return_arrow_operator] = sym_return_arrow_operator,
  [sym_source_file] = sym_source_file,
  [sym_nidl_document] = sym_nidl_document,
  [sym_nidl_member] = sym_nidl_member,
  [sym_opaque_declaration] = sym_opaque_declaration,
  [sym_nidl_struct_declaration] = sym_nidl_struct_declaration,
  [sym_nidl_field_declaration] = sym_nidl_field_declaration,
  [sym_nidl_enum_declaration] = sym_nidl_enum_declaration,
  [sym_nidl_enum_variant] = sym_nidl_enum_variant,
  [sym_host_function_declaration] = sym_host_function_declaration,
  [sym_request_policy] = sym_request_policy,
  [sym_fuel_clause] = sym_fuel_clause,
  [sym_nidl_parameter_list] = sym_nidl_parameter_list,
  [sym_nidl_parameter] = sym_nidl_parameter,
  [sym_export_declaration] = sym_export_declaration,
  [sym_nidl_type] = sym_nidl_type,
  [sym_nidl_generic_type] = sym_nidl_generic_type,
  [sym_nidl_type_argument_list] = sym_nidl_type_argument_list,
  [sym_nidl_type_identifier] = sym_nidl_type_identifier,
  [sym_host_mode_keyword] = sym_host_mode_keyword,
  [sym_cancel_policy_keyword] = sym_cancel_policy_keyword,
  [sym_abandon_policy_keyword] = sym_abandon_policy_keyword,
  [sym_nidl_builtin_type] = sym_nidl_builtin_type,
  [aux_sym_nidl_document_repeat1] = aux_sym_nidl_document_repeat1,
  [aux_sym_nidl_struct_declaration_repeat1] = aux_sym_nidl_struct_declaration_repeat1,
  [aux_sym_nidl_enum_declaration_repeat1] = aux_sym_nidl_enum_declaration_repeat1,
  [aux_sym_nidl_parameter_list_repeat1] = aux_sym_nidl_parameter_list_repeat1,
  [aux_sym_nidl_type_argument_list_repeat1] = aux_sym_nidl_type_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_nidl_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_interface_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_opaque_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_nidl_struct_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_nidl_enum_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_nidl_function_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_export_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_sync] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_request] = {
    .visible = true,
    .named = false,
  },
  [sym_fuel_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_return_error] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cancel_task] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trap] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rune] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_host_request] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_resource_token] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_token] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_snapshot] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_array] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_buffer] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Option] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Result] = {
    .visible = true,
    .named = false,
  },
  [sym_void_type] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_return_arrow_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_nidl_document] = {
    .visible = true,
    .named = true,
  },
  [sym_nidl_member] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_opaque_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_nidl_struct_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_nidl_field_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_nidl_enum_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_nidl_enum_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_host_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_request_policy] = {
    .visible = true,
    .named = true,
  },
  [sym_fuel_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_nidl_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_nidl_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_export_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_nidl_type] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_nidl_generic_type] = {
    .visible = true,
    .named = true,
  },
  [sym_nidl_type_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_nidl_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_host_mode_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_cancel_policy_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_abandon_policy_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_nidl_builtin_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_nidl_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_nidl_struct_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_nidl_enum_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_nidl_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_nidl_type_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_abandon = 1,
  field_amount = 2,
  field_arguments = 3,
  field_arrow = 4,
  field_cancel = 5,
  field_keyword = 6,
  field_mode = 7,
  field_name = 8,
  field_parameters = 9,
  field_payload = 10,
  field_return_type = 11,
  field_type = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_abandon] = "abandon",
  [field_amount] = "amount",
  [field_arguments] = "arguments",
  [field_arrow] = "arrow",
  [field_cancel] = "cancel",
  [field_keyword] = "keyword",
  [field_mode] = "mode",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_payload] = "payload",
  [field_return_type] = "return_type",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 5},
  [6] = {.index = 11, .length = 2},
  [7] = {.index = 13, .length = 2},
  [8] = {.index = 15, .length = 2},
  [9] = {.index = 17, .length = 6},
  [10] = {.index = 23, .length = 6},
  [11] = {.index = 29, .length = 6},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_keyword, 0},
    {field_name, 1},
  [2] =
    {field_amount, 1},
  [3] =
    {field_name, 0},
  [4] =
    {field_name, 0},
    {field_type, 2},
  [6] =
    {field_arrow, 3},
    {field_keyword, 0},
    {field_name, 1},
    {field_parameters, 2},
    {field_return_type, 4},
  [11] =
    {field_arguments, 1},
    {field_name, 0},
  [13] =
    {field_abandon, 3},
    {field_cancel, 1},
  [15] =
    {field_name, 0},
    {field_payload, 2},
  [17] =
    {field_arrow, 4},
    {field_keyword, 1},
    {field_mode, 0},
    {field_name, 2},
    {field_parameters, 3},
    {field_return_type, 5},
  [23] =
    {field_arrow, 5},
    {field_keyword, 2},
    {field_mode, 0},
    {field_name, 3},
    {field_parameters, 4},
    {field_return_type, 6},
  [29] =
    {field_arrow, 6},
    {field_keyword, 3},
    {field_mode, 0},
    {field_name, 4},
    {field_parameters, 5},
    {field_return_type, 7},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_nidl_member,
  sym_nidl_type,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_nidl_member] = {.index = 0, .length = 5},
  [sym_nidl_type] = {.index = 5, .length = 3},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_export_declaration,
    sym_host_function_declaration,
    sym_nidl_enum_declaration,
    sym_nidl_struct_declaration,
    sym_opaque_declaration,
  [5] =
    sym_nidl_builtin_type,
    sym_nidl_generic_type,
    sym_nidl_type_identifier,
};

static const TSCharacterRange sym_nidl_identifier_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '\''}, {'+', '+'}, {'.', '.'}, {'0', '9'}, {'=', '='}, {'?', 'z'},
  {'|', '|'}, {'~', 0x17e}, {0x180, 0x2129}, {0x212b, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '(', 10,
        ')', 11,
        ',', 9,
        '-', 2,
        ':', 8,
        ';', 7,
        '<', 12,
        '>', 13,
        '{', 5,
        '}', 6,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (lookahead != 0 &&
          (lookahead < '(' || '*' < lookahead) &&
          (lookahead < '/' || '<' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == ',') ADVANCE(9);
      if (lookahead == '}') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if ((!eof && set_contains(sym_nidl_identifier_character_set_1, 12, lookahead))) ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(17);
      END_STATE();
    case 3:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_nidl_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if ((!eof && set_contains(sym_nidl_identifier_character_set_1, 12, lookahead))) ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_nidl_identifier);
      if ((!eof && set_contains(sym_nidl_identifier_character_set_1, 12, lookahead))) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_return_arrow_operator);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'O', 1,
        'R', 2,
        'a', 3,
        'b', 4,
        'c', 5,
        'e', 6,
        'f', 7,
        'h', 8,
        'i', 9,
        'o', 10,
        'r', 11,
        's', 12,
        't', 13,
        'v', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'p') ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(18);
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(21);
      if (lookahead == 'x') ADVANCE(22);
      END_STATE();
    case 7:
      if (lookahead == '3') ADVANCE(23);
      if (lookahead == '6') ADVANCE(24);
      if (lookahead == 'n') ADVANCE(25);
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == '3') ADVANCE(28);
      if (lookahead == '6') ADVANCE(29);
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 10:
      if (lookahead == 'p') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(32);
      if (lookahead == 'u') ADVANCE(33);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(34);
      if (lookahead == 't') ADVANCE(35);
      if (lookahead == 'y') ADVANCE(36);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(37);
      if (lookahead == 'r') ADVANCE(38);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(44);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(45);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(46);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(47);
      END_STATE();
    case 23:
      if (lookahead == '2') ADVANCE(48);
      END_STATE();
    case 24:
      if (lookahead == '4') ADVANCE(49);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_nidl_function_keyword);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(51);
      END_STATE();
    case 28:
      if (lookahead == '2') ADVANCE(52);
      END_STATE();
    case 29:
      if (lookahead == '4') ADVANCE(53);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(55);
      END_STATE();
    case 32:
      if (lookahead == 'q') ADVANCE(56);
      if (lookahead == 's') ADVANCE(57);
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(59);
      END_STATE();
    case 34:
      if (lookahead == 'a') ADVANCE(60);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(61);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(62);
      END_STATE();
    case 37:
      if (lookahead == 'k') ADVANCE(63);
      END_STATE();
    case 38:
      if (lookahead == 'a') ADVANCE(64);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(65);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(66);
      END_STATE();
    case 41:
      if (lookahead == 'u') ADVANCE(67);
      END_STATE();
    case 42:
      if (lookahead == 'a') ADVANCE(68);
      END_STATE();
    case 43:
      if (lookahead == 'l') ADVANCE(69);
      END_STATE();
    case 44:
      if (lookahead == 'f') ADVANCE(70);
      END_STATE();
    case 45:
      if (lookahead == 'c') ADVANCE(71);
      END_STATE();
    case 46:
      if (lookahead == 'm') ADVANCE(72);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(73);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_f32);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_f64);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(74);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_i64);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 55:
      if (lookahead == 'q') ADVANCE(77);
      END_STATE();
    case 56:
      if (lookahead == 'u') ADVANCE(78);
      END_STATE();
    case 57:
      if (lookahead == 'o') ADVANCE(79);
      END_STATE();
    case 58:
      if (lookahead == 'u') ADVANCE(80);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 60:
      if (lookahead == 'p') ADVANCE(82);
      END_STATE();
    case 61:
      if (lookahead == 'i') ADVANCE(83);
      if (lookahead == 'u') ADVANCE(84);
      END_STATE();
    case 62:
      if (lookahead == 'c') ADVANCE(85);
      END_STATE();
    case 63:
      if (lookahead == 'e') ADVANCE(86);
      END_STATE();
    case 64:
      if (lookahead == 'p') ADVANCE(87);
      END_STATE();
    case 65:
      if (lookahead == 'd') ADVANCE(88);
      END_STATE();
    case 66:
      if (lookahead == 'o') ADVANCE(89);
      END_STATE();
    case 67:
      if (lookahead == 'l') ADVANCE(90);
      END_STATE();
    case 68:
      if (lookahead == 'y') ADVANCE(91);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 70:
      if (lookahead == 'e') ADVANCE(92);
      END_STATE();
    case 71:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_nidl_enum_keyword);
      END_STATE();
    case 73:
      if (lookahead == 'r') ADVANCE(94);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_fuel_keyword);
      END_STATE();
    case 75:
      if (lookahead == '_') ADVANCE(95);
      END_STATE();
    case 76:
      if (lookahead == 'r') ADVANCE(96);
      END_STATE();
    case 77:
      if (lookahead == 'u') ADVANCE(97);
      END_STATE();
    case 78:
      if (lookahead == 'e') ADVANCE(98);
      END_STATE();
    case 79:
      if (lookahead == 'u') ADVANCE(99);
      END_STATE();
    case 80:
      if (lookahead == 'r') ADVANCE(100);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_rune);
      END_STATE();
    case 82:
      if (lookahead == 's') ADVANCE(101);
      END_STATE();
    case 83:
      if (lookahead == 'n') ADVANCE(102);
      END_STATE();
    case 84:
      if (lookahead == 'c') ADVANCE(103);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_sync);
      END_STATE();
    case 86:
      if (lookahead == 'n') ADVANCE(104);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_trap);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_void_type);
      END_STATE();
    case 89:
      if (lookahead == 'n') ADVANCE(105);
      END_STATE();
    case 90:
      if (lookahead == 't') ADVANCE(106);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_array);
      END_STATE();
    case 92:
      if (lookahead == 'r') ADVANCE(107);
      END_STATE();
    case 93:
      if (lookahead == 'l') ADVANCE(108);
      END_STATE();
    case 94:
      if (lookahead == 't') ADVANCE(109);
      END_STATE();
    case 95:
      if (lookahead == 'r') ADVANCE(110);
      END_STATE();
    case 96:
      if (lookahead == 'f') ADVANCE(111);
      END_STATE();
    case 97:
      if (lookahead == 'e') ADVANCE(112);
      END_STATE();
    case 98:
      if (lookahead == 's') ADVANCE(113);
      END_STATE();
    case 99:
      if (lookahead == 'r') ADVANCE(114);
      END_STATE();
    case 100:
      if (lookahead == 'n') ADVANCE(115);
      END_STATE();
    case 101:
      if (lookahead == 'h') ADVANCE(116);
      END_STATE();
    case 102:
      if (lookahead == 'g') ADVANCE(117);
      END_STATE();
    case 103:
      if (lookahead == 't') ADVANCE(118);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_token);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_Option);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_Result);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_buffer);
      END_STATE();
    case 108:
      if (lookahead == '_') ADVANCE(119);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_export_keyword);
      END_STATE();
    case 110:
      if (lookahead == 'e') ADVANCE(120);
      END_STATE();
    case 111:
      if (lookahead == 'a') ADVANCE(121);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_opaque_keyword);
      END_STATE();
    case 113:
      if (lookahead == 't') ADVANCE(122);
      END_STATE();
    case 114:
      if (lookahead == 'c') ADVANCE(123);
      END_STATE();
    case 115:
      if (lookahead == '_') ADVANCE(124);
      END_STATE();
    case 116:
      if (lookahead == 'o') ADVANCE(125);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_nidl_struct_keyword);
      END_STATE();
    case 119:
      if (lookahead == 't') ADVANCE(126);
      END_STATE();
    case 120:
      if (lookahead == 'q') ADVANCE(127);
      END_STATE();
    case 121:
      if (lookahead == 'c') ADVANCE(128);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_request);
      END_STATE();
    case 123:
      if (lookahead == 'e') ADVANCE(129);
      END_STATE();
    case 124:
      if (lookahead == 'e') ADVANCE(130);
      END_STATE();
    case 125:
      if (lookahead == 't') ADVANCE(131);
      END_STATE();
    case 126:
      if (lookahead == 'a') ADVANCE(132);
      END_STATE();
    case 127:
      if (lookahead == 'u') ADVANCE(133);
      END_STATE();
    case 128:
      if (lookahead == 'e') ADVANCE(134);
      END_STATE();
    case 129:
      if (lookahead == '_') ADVANCE(135);
      END_STATE();
    case 130:
      if (lookahead == 'r') ADVANCE(136);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_snapshot);
      END_STATE();
    case 132:
      if (lookahead == 's') ADVANCE(137);
      END_STATE();
    case 133:
      if (lookahead == 'e') ADVANCE(138);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_interface_keyword);
      END_STATE();
    case 135:
      if (lookahead == 't') ADVANCE(139);
      END_STATE();
    case 136:
      if (lookahead == 'r') ADVANCE(140);
      END_STATE();
    case 137:
      if (lookahead == 'k') ADVANCE(141);
      END_STATE();
    case 138:
      if (lookahead == 's') ADVANCE(142);
      END_STATE();
    case 139:
      if (lookahead == 'o') ADVANCE(143);
      END_STATE();
    case 140:
      if (lookahead == 'o') ADVANCE(144);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(anon_sym_cancel_task);
      END_STATE();
    case 142:
      if (lookahead == 't') ADVANCE(145);
      END_STATE();
    case 143:
      if (lookahead == 'k') ADVANCE(146);
      END_STATE();
    case 144:
      if (lookahead == 'r') ADVANCE(147);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_host_request);
      END_STATE();
    case 146:
      if (lookahead == 'e') ADVANCE(148);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(anon_sym_return_error);
      END_STATE();
    case 148:
      if (lookahead == 'n') ADVANCE(149);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(anon_sym_resource_token);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 3},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_nidl_identifier] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_interface_keyword] = ACTIONS(1),
    [sym_opaque_keyword] = ACTIONS(1),
    [sym_nidl_struct_keyword] = ACTIONS(1),
    [sym_nidl_enum_keyword] = ACTIONS(1),
    [sym_nidl_function_keyword] = ACTIONS(1),
    [sym_export_keyword] = ACTIONS(1),
    [anon_sym_sync] = ACTIONS(1),
    [anon_sym_request] = ACTIONS(1),
    [sym_fuel_keyword] = ACTIONS(1),
    [anon_sym_return_error] = ACTIONS(1),
    [anon_sym_cancel_task] = ACTIONS(1),
    [anon_sym_trap] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_i64] = ACTIONS(1),
    [anon_sym_f32] = ACTIONS(1),
    [anon_sym_f64] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_rune] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_host_request] = ACTIONS(1),
    [anon_sym_resource_token] = ACTIONS(1),
    [anon_sym_token] = ACTIONS(1),
    [anon_sym_snapshot] = ACTIONS(1),
    [anon_sym_array] = ACTIONS(1),
    [anon_sym_buffer] = ACTIONS(1),
    [anon_sym_Option] = ACTIONS(1),
    [anon_sym_Result] = ACTIONS(1),
    [sym_void_type] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_return_arrow_operator] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(67),
    [sym_nidl_document] = STATE(86),
    [sym_interface_keyword] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(5), 1,
      sym_nidl_identifier,
    ACTIONS(9), 1,
      sym_void_type,
    STATE(38), 1,
      sym_nidl_generic_type,
    STATE(97), 1,
      sym_nidl_type,
    STATE(25), 2,
      sym_nidl_type_identifier,
      sym_nidl_builtin_type,
    ACTIONS(7), 16,
      anon_sym_request,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_rune,
      anon_sym_string,
      anon_sym_host_request,
      anon_sym_resource_token,
      anon_sym_token,
      anon_sym_snapshot,
      anon_sym_array,
      anon_sym_buffer,
      anon_sym_Option,
      anon_sym_Result,
  [35] = 5,
    ACTIONS(5), 1,
      sym_nidl_identifier,
    STATE(38), 1,
      sym_nidl_generic_type,
    STATE(73), 1,
      sym_nidl_type,
    STATE(25), 2,
      sym_nidl_type_identifier,
      sym_nidl_builtin_type,
    ACTIONS(7), 16,
      anon_sym_request,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_rune,
      anon_sym_string,
      anon_sym_host_request,
      anon_sym_resource_token,
      anon_sym_token,
      anon_sym_snapshot,
      anon_sym_array,
      anon_sym_buffer,
      anon_sym_Option,
      anon_sym_Result,
  [67] = 5,
    ACTIONS(5), 1,
      sym_nidl_identifier,
    STATE(38), 1,
      sym_nidl_generic_type,
    STATE(74), 1,
      sym_nidl_type,
    STATE(25), 2,
      sym_nidl_type_identifier,
      sym_nidl_builtin_type,
    ACTIONS(7), 16,
      anon_sym_request,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_rune,
      anon_sym_string,
      anon_sym_host_request,
      anon_sym_resource_token,
      anon_sym_token,
      anon_sym_snapshot,
      anon_sym_array,
      anon_sym_buffer,
      anon_sym_Option,
      anon_sym_Result,
  [99] = 5,
    ACTIONS(5), 1,
      sym_nidl_identifier,
    STATE(38), 1,
      sym_nidl_generic_type,
    STATE(101), 1,
      sym_nidl_type,
    STATE(25), 2,
      sym_nidl_type_identifier,
      sym_nidl_builtin_type,
    ACTIONS(7), 16,
      anon_sym_request,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_rune,
      anon_sym_string,
      anon_sym_host_request,
      anon_sym_resource_token,
      anon_sym_token,
      anon_sym_snapshot,
      anon_sym_array,
      anon_sym_buffer,
      anon_sym_Option,
      anon_sym_Result,
  [131] = 5,
    ACTIONS(5), 1,
      sym_nidl_identifier,
    STATE(38), 1,
      sym_nidl_generic_type,
    STATE(61), 1,
      sym_nidl_type,
    STATE(25), 2,
      sym_nidl_type_identifier,
      sym_nidl_builtin_type,
    ACTIONS(7), 16,
      anon_sym_request,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_rune,
      anon_sym_string,
      anon_sym_host_request,
      anon_sym_resource_token,
      anon_sym_token,
      anon_sym_snapshot,
      anon_sym_array,
      anon_sym_buffer,
      anon_sym_Option,
      anon_sym_Result,
  [163] = 5,
    ACTIONS(5), 1,
      sym_nidl_identifier,
    STATE(38), 1,
      sym_nidl_generic_type,
    STATE(90), 1,
      sym_nidl_type,
    STATE(25), 2,
      sym_nidl_type_identifier,
      sym_nidl_builtin_type,
    ACTIONS(7), 16,
      anon_sym_request,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_rune,
      anon_sym_string,
      anon_sym_host_request,
      anon_sym_resource_token,
      anon_sym_token,
      anon_sym_snapshot,
      anon_sym_array,
      anon_sym_buffer,
      anon_sym_Option,
      anon_sym_Result,
  [195] = 5,
    ACTIONS(5), 1,
      sym_nidl_identifier,
    STATE(38), 1,
      sym_nidl_generic_type,
    STATE(96), 1,
      sym_nidl_type,
    STATE(25), 2,
      sym_nidl_type_identifier,
      sym_nidl_builtin_type,
    ACTIONS(7), 16,
      anon_sym_request,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_rune,
      anon_sym_string,
      anon_sym_host_request,
      anon_sym_resource_token,
      anon_sym_token,
      anon_sym_snapshot,
      anon_sym_array,
      anon_sym_buffer,
      anon_sym_Option,
      anon_sym_Result,
  [227] = 5,
    ACTIONS(5), 1,
      sym_nidl_identifier,
    STATE(38), 1,
      sym_nidl_generic_type,
    STATE(49), 1,
      sym_nidl_type,
    STATE(25), 2,
      sym_nidl_type_identifier,
      sym_nidl_builtin_type,
    ACTIONS(7), 16,
      anon_sym_request,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_rune,
      anon_sym_string,
      anon_sym_host_request,
      anon_sym_resource_token,
      anon_sym_token,
      anon_sym_snapshot,
      anon_sym_array,
      anon_sym_buffer,
      anon_sym_Option,
      anon_sym_Result,
  [259] = 5,
    ACTIONS(5), 1,
      sym_nidl_identifier,
    STATE(38), 1,
      sym_nidl_generic_type,
    STATE(66), 1,
      sym_nidl_type,
    STATE(25), 2,
      sym_nidl_type_identifier,
      sym_nidl_builtin_type,
    ACTIONS(7), 16,
      anon_sym_request,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_rune,
      anon_sym_string,
      anon_sym_host_request,
      anon_sym_resource_token,
      anon_sym_token,
      anon_sym_snapshot,
      anon_sym_array,
      anon_sym_buffer,
      anon_sym_Option,
      anon_sym_Result,
  [291] = 9,
    ACTIONS(11), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 1,
      sym_opaque_keyword,
    ACTIONS(15), 1,
      sym_nidl_struct_keyword,
    ACTIONS(17), 1,
      sym_nidl_enum_keyword,
    ACTIONS(19), 1,
      sym_export_keyword,
    STATE(26), 1,
      sym_host_mode_keyword,
    ACTIONS(21), 2,
      anon_sym_sync,
      anon_sym_request,
    STATE(12), 2,
      sym_nidl_member,
      aux_sym_nidl_document_repeat1,
    STATE(17), 5,
      sym_opaque_declaration,
      sym_nidl_struct_declaration,
      sym_nidl_enum_declaration,
      sym_host_function_declaration,
      sym_export_declaration,
  [325] = 9,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    ACTIONS(25), 1,
      sym_opaque_keyword,
    ACTIONS(28), 1,
      sym_nidl_struct_keyword,
    ACTIONS(31), 1,
      sym_nidl_enum_keyword,
    ACTIONS(34), 1,
      sym_export_keyword,
    STATE(26), 1,
      sym_host_mode_keyword,
    ACTIONS(37), 2,
      anon_sym_sync,
      anon_sym_request,
    STATE(12), 2,
      sym_nidl_member,
      aux_sym_nidl_document_repeat1,
    STATE(17), 5,
      sym_opaque_declaration,
      sym_nidl_struct_declaration,
      sym_nidl_enum_declaration,
      sym_host_function_declaration,
      sym_export_declaration,
  [359] = 9,
    ACTIONS(13), 1,
      sym_opaque_keyword,
    ACTIONS(15), 1,
      sym_nidl_struct_keyword,
    ACTIONS(17), 1,
      sym_nidl_enum_keyword,
    ACTIONS(19), 1,
      sym_export_keyword,
    ACTIONS(40), 1,
      anon_sym_RBRACE,
    STATE(26), 1,
      sym_host_mode_keyword,
    ACTIONS(21), 2,
      anon_sym_sync,
      anon_sym_request,
    STATE(11), 2,
      sym_nidl_member,
      aux_sym_nidl_document_repeat1,
    STATE(17), 5,
      sym_opaque_declaration,
      sym_nidl_struct_declaration,
      sym_nidl_enum_declaration,
      sym_host_function_declaration,
      sym_export_declaration,
  [393] = 1,
    ACTIONS(42), 7,
      anon_sym_RBRACE,
      sym_opaque_keyword,
      sym_nidl_struct_keyword,
      sym_nidl_enum_keyword,
      sym_export_keyword,
      anon_sym_sync,
      anon_sym_request,
  [403] = 1,
    ACTIONS(44), 7,
      anon_sym_RBRACE,
      sym_opaque_keyword,
      sym_nidl_struct_keyword,
      sym_nidl_enum_keyword,
      sym_export_keyword,
      anon_sym_sync,
      anon_sym_request,
  [413] = 1,
    ACTIONS(46), 7,
      anon_sym_RBRACE,
      sym_opaque_keyword,
      sym_nidl_struct_keyword,
      sym_nidl_enum_keyword,
      sym_export_keyword,
      anon_sym_sync,
      anon_sym_request,
  [423] = 1,
    ACTIONS(48), 7,
      anon_sym_RBRACE,
      sym_opaque_keyword,
      sym_nidl_struct_keyword,
      sym_nidl_enum_keyword,
      sym_export_keyword,
      anon_sym_sync,
      anon_sym_request,
  [433] = 1,
    ACTIONS(50), 7,
      anon_sym_RBRACE,
      sym_opaque_keyword,
      sym_nidl_struct_keyword,
      sym_nidl_enum_keyword,
      sym_export_keyword,
      anon_sym_sync,
      anon_sym_request,
  [443] = 1,
    ACTIONS(52), 7,
      anon_sym_RBRACE,
      sym_opaque_keyword,
      sym_nidl_struct_keyword,
      sym_nidl_enum_keyword,
      sym_export_keyword,
      anon_sym_sync,
      anon_sym_request,
  [453] = 1,
    ACTIONS(54), 7,
      anon_sym_RBRACE,
      sym_opaque_keyword,
      sym_nidl_struct_keyword,
      sym_nidl_enum_keyword,
      sym_export_keyword,
      anon_sym_sync,
      anon_sym_request,
  [463] = 1,
    ACTIONS(56), 7,
      anon_sym_RBRACE,
      sym_opaque_keyword,
      sym_nidl_struct_keyword,
      sym_nidl_enum_keyword,
      sym_export_keyword,
      anon_sym_sync,
      anon_sym_request,
  [473] = 1,
    ACTIONS(58), 7,
      anon_sym_RBRACE,
      sym_opaque_keyword,
      sym_nidl_struct_keyword,
      sym_nidl_enum_keyword,
      sym_export_keyword,
      anon_sym_sync,
      anon_sym_request,
  [483] = 1,
    ACTIONS(60), 7,
      anon_sym_RBRACE,
      sym_opaque_keyword,
      sym_nidl_struct_keyword,
      sym_nidl_enum_keyword,
      sym_export_keyword,
      anon_sym_sync,
      anon_sym_request,
  [493] = 1,
    ACTIONS(62), 6,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
  [502] = 3,
    ACTIONS(66), 1,
      anon_sym_LT,
    STATE(36), 1,
      sym_nidl_type_argument_list,
    ACTIONS(64), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT,
  [515] = 5,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      sym_nidl_function_keyword,
    ACTIONS(72), 1,
      sym_fuel_keyword,
    STATE(44), 1,
      sym_request_policy,
    STATE(94), 1,
      sym_fuel_clause,
  [531] = 1,
    ACTIONS(74), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
  [539] = 2,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_nidl_identifier,
  [548] = 3,
    ACTIONS(80), 1,
      sym_nidl_identifier,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    STATE(29), 2,
      sym_nidl_field_declaration,
      aux_sym_nidl_struct_declaration_repeat1,
  [559] = 4,
    ACTIONS(85), 1,
      sym_nidl_identifier,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      aux_sym_nidl_enum_declaration_repeat1,
    STATE(42), 1,
      sym_nidl_enum_variant,
  [572] = 4,
    ACTIONS(85), 1,
      sym_nidl_identifier,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      aux_sym_nidl_enum_declaration_repeat1,
    STATE(42), 1,
      sym_nidl_enum_variant,
  [585] = 3,
    ACTIONS(91), 1,
      sym_nidl_identifier,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    STATE(34), 2,
      sym_nidl_field_declaration,
      aux_sym_nidl_struct_declaration_repeat1,
  [596] = 4,
    ACTIONS(95), 1,
      sym_nidl_identifier,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      aux_sym_nidl_enum_declaration_repeat1,
    STATE(42), 1,
      sym_nidl_enum_variant,
  [609] = 3,
    ACTIONS(91), 1,
      sym_nidl_identifier,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    STATE(29), 2,
      sym_nidl_field_declaration,
      aux_sym_nidl_struct_declaration_repeat1,
  [620] = 1,
    ACTIONS(102), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT,
  [627] = 1,
    ACTIONS(104), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT,
  [634] = 1,
    ACTIONS(106), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT,
  [641] = 1,
    ACTIONS(64), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT,
  [648] = 3,
    ACTIONS(108), 1,
      anon_sym_COMMA,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      aux_sym_nidl_parameter_list_repeat1,
  [658] = 2,
    STATE(69), 1,
      sym_abandon_policy_keyword,
    ACTIONS(112), 2,
      anon_sym_return_error,
      anon_sym_trap,
  [666] = 1,
    ACTIONS(114), 3,
      anon_sym_LPAREN,
      sym_nidl_function_keyword,
      sym_fuel_keyword,
  [672] = 2,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(116), 2,
      anon_sym_RBRACE,
      sym_nidl_identifier,
  [680] = 2,
    STATE(91), 1,
      sym_cancel_policy_keyword,
    ACTIONS(120), 2,
      anon_sym_return_error,
      anon_sym_cancel_task,
  [688] = 3,
    ACTIONS(72), 1,
      sym_fuel_keyword,
    ACTIONS(122), 1,
      sym_nidl_function_keyword,
    STATE(98), 1,
      sym_fuel_clause,
  [698] = 3,
    ACTIONS(108), 1,
      anon_sym_COMMA,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      aux_sym_nidl_parameter_list_repeat1,
  [708] = 3,
    ACTIONS(126), 1,
      anon_sym_COMMA,
    ACTIONS(128), 1,
      anon_sym_GT,
    STATE(51), 1,
      aux_sym_nidl_type_argument_list_repeat1,
  [718] = 1,
    ACTIONS(130), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_nidl_identifier,
  [724] = 3,
    ACTIONS(132), 1,
      anon_sym_COMMA,
    ACTIONS(135), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      aux_sym_nidl_parameter_list_repeat1,
  [734] = 3,
    ACTIONS(126), 1,
      anon_sym_COMMA,
    ACTIONS(137), 1,
      anon_sym_GT,
    STATE(46), 1,
      aux_sym_nidl_type_argument_list_repeat1,
  [744] = 3,
    ACTIONS(139), 1,
      sym_nidl_identifier,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      sym_nidl_parameter,
  [754] = 3,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    ACTIONS(146), 1,
      anon_sym_GT,
    STATE(51), 1,
      aux_sym_nidl_type_argument_list_repeat1,
  [764] = 2,
    ACTIONS(148), 1,
      anon_sym_LPAREN,
    STATE(84), 1,
      sym_nidl_parameter_list,
  [771] = 2,
    ACTIONS(150), 1,
      sym_nidl_identifier,
    STATE(76), 1,
      sym_nidl_type_identifier,
  [778] = 1,
    ACTIONS(98), 2,
      anon_sym_RBRACE,
      sym_nidl_identifier,
  [783] = 2,
    ACTIONS(150), 1,
      sym_nidl_identifier,
    STATE(79), 1,
      sym_nidl_type_identifier,
  [790] = 2,
    ACTIONS(139), 1,
      sym_nidl_identifier,
    STATE(60), 1,
      sym_nidl_parameter,
  [797] = 2,
    ACTIONS(148), 1,
      anon_sym_LPAREN,
    STATE(71), 1,
      sym_nidl_parameter_list,
  [804] = 2,
    ACTIONS(148), 1,
      anon_sym_LPAREN,
    STATE(85), 1,
      sym_nidl_parameter_list,
  [811] = 2,
    ACTIONS(150), 1,
      sym_nidl_identifier,
    STATE(80), 1,
      sym_nidl_type_identifier,
  [818] = 1,
    ACTIONS(135), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [823] = 1,
    ACTIONS(152), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [828] = 1,
    ACTIONS(154), 2,
      sym_nidl_function_keyword,
      sym_fuel_keyword,
  [833] = 1,
    ACTIONS(156), 2,
      anon_sym_RBRACE,
      sym_nidl_identifier,
  [838] = 2,
    ACTIONS(148), 1,
      anon_sym_LPAREN,
    STATE(87), 1,
      sym_nidl_parameter_list,
  [845] = 2,
    ACTIONS(150), 1,
      sym_nidl_identifier,
    STATE(75), 1,
      sym_nidl_type_identifier,
  [852] = 1,
    ACTIONS(146), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [857] = 1,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
  [861] = 1,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
  [865] = 1,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
  [869] = 1,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
  [873] = 1,
    ACTIONS(166), 1,
      sym_return_arrow_operator,
  [877] = 1,
    ACTIONS(168), 1,
      sym_nidl_identifier,
  [881] = 1,
    ACTIONS(170), 1,
      anon_sym_SEMI,
  [885] = 1,
    ACTIONS(172), 1,
      anon_sym_RPAREN,
  [889] = 1,
    ACTIONS(174), 1,
      anon_sym_LBRACE,
  [893] = 1,
    ACTIONS(176), 1,
      anon_sym_LBRACE,
  [897] = 1,
    ACTIONS(178), 1,
      sym_return_arrow_operator,
  [901] = 1,
    ACTIONS(180), 1,
      anon_sym_COLON,
  [905] = 1,
    ACTIONS(182), 1,
      anon_sym_LBRACE,
  [909] = 1,
    ACTIONS(184), 1,
      anon_sym_SEMI,
  [913] = 1,
    ACTIONS(186), 1,
      sym_nidl_identifier,
  [917] = 1,
    ACTIONS(188), 1,
      sym_integer_literal,
  [921] = 1,
    ACTIONS(190), 1,
      sym_nidl_identifier,
  [925] = 1,
    ACTIONS(192), 1,
      sym_return_arrow_operator,
  [929] = 1,
    ACTIONS(194), 1,
      sym_return_arrow_operator,
  [933] = 1,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
  [937] = 1,
    ACTIONS(198), 1,
      sym_return_arrow_operator,
  [941] = 1,
    ACTIONS(200), 1,
      sym_return_arrow_operator,
  [945] = 1,
    ACTIONS(202), 1,
      anon_sym_COMMA,
  [949] = 1,
    ACTIONS(204), 1,
      anon_sym_SEMI,
  [953] = 1,
    ACTIONS(206), 1,
      anon_sym_COMMA,
  [957] = 1,
    ACTIONS(208), 1,
      sym_return_arrow_operator,
  [961] = 1,
    ACTIONS(210), 1,
      sym_nidl_function_keyword,
  [965] = 1,
    ACTIONS(122), 1,
      sym_nidl_function_keyword,
  [969] = 1,
    ACTIONS(212), 1,
      sym_nidl_identifier,
  [973] = 1,
    ACTIONS(214), 1,
      anon_sym_SEMI,
  [977] = 1,
    ACTIONS(216), 1,
      anon_sym_SEMI,
  [981] = 1,
    ACTIONS(218), 1,
      sym_nidl_function_keyword,
  [985] = 1,
    ACTIONS(220), 1,
      ts_builtin_sym_end,
  [989] = 1,
    ACTIONS(222), 1,
      anon_sym_COLON,
  [993] = 1,
    ACTIONS(224), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 67,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 131,
  [SMALL_STATE(7)] = 163,
  [SMALL_STATE(8)] = 195,
  [SMALL_STATE(9)] = 227,
  [SMALL_STATE(10)] = 259,
  [SMALL_STATE(11)] = 291,
  [SMALL_STATE(12)] = 325,
  [SMALL_STATE(13)] = 359,
  [SMALL_STATE(14)] = 393,
  [SMALL_STATE(15)] = 403,
  [SMALL_STATE(16)] = 413,
  [SMALL_STATE(17)] = 423,
  [SMALL_STATE(18)] = 433,
  [SMALL_STATE(19)] = 443,
  [SMALL_STATE(20)] = 453,
  [SMALL_STATE(21)] = 463,
  [SMALL_STATE(22)] = 473,
  [SMALL_STATE(23)] = 483,
  [SMALL_STATE(24)] = 493,
  [SMALL_STATE(25)] = 502,
  [SMALL_STATE(26)] = 515,
  [SMALL_STATE(27)] = 531,
  [SMALL_STATE(28)] = 539,
  [SMALL_STATE(29)] = 548,
  [SMALL_STATE(30)] = 559,
  [SMALL_STATE(31)] = 572,
  [SMALL_STATE(32)] = 585,
  [SMALL_STATE(33)] = 596,
  [SMALL_STATE(34)] = 609,
  [SMALL_STATE(35)] = 620,
  [SMALL_STATE(36)] = 627,
  [SMALL_STATE(37)] = 634,
  [SMALL_STATE(38)] = 641,
  [SMALL_STATE(39)] = 648,
  [SMALL_STATE(40)] = 658,
  [SMALL_STATE(41)] = 666,
  [SMALL_STATE(42)] = 672,
  [SMALL_STATE(43)] = 680,
  [SMALL_STATE(44)] = 688,
  [SMALL_STATE(45)] = 698,
  [SMALL_STATE(46)] = 708,
  [SMALL_STATE(47)] = 718,
  [SMALL_STATE(48)] = 724,
  [SMALL_STATE(49)] = 734,
  [SMALL_STATE(50)] = 744,
  [SMALL_STATE(51)] = 754,
  [SMALL_STATE(52)] = 764,
  [SMALL_STATE(53)] = 771,
  [SMALL_STATE(54)] = 778,
  [SMALL_STATE(55)] = 783,
  [SMALL_STATE(56)] = 790,
  [SMALL_STATE(57)] = 797,
  [SMALL_STATE(58)] = 804,
  [SMALL_STATE(59)] = 811,
  [SMALL_STATE(60)] = 818,
  [SMALL_STATE(61)] = 823,
  [SMALL_STATE(62)] = 828,
  [SMALL_STATE(63)] = 833,
  [SMALL_STATE(64)] = 838,
  [SMALL_STATE(65)] = 845,
  [SMALL_STATE(66)] = 852,
  [SMALL_STATE(67)] = 857,
  [SMALL_STATE(68)] = 861,
  [SMALL_STATE(69)] = 865,
  [SMALL_STATE(70)] = 869,
  [SMALL_STATE(71)] = 873,
  [SMALL_STATE(72)] = 877,
  [SMALL_STATE(73)] = 881,
  [SMALL_STATE(74)] = 885,
  [SMALL_STATE(75)] = 889,
  [SMALL_STATE(76)] = 893,
  [SMALL_STATE(77)] = 897,
  [SMALL_STATE(78)] = 901,
  [SMALL_STATE(79)] = 905,
  [SMALL_STATE(80)] = 909,
  [SMALL_STATE(81)] = 913,
  [SMALL_STATE(82)] = 917,
  [SMALL_STATE(83)] = 921,
  [SMALL_STATE(84)] = 925,
  [SMALL_STATE(85)] = 929,
  [SMALL_STATE(86)] = 933,
  [SMALL_STATE(87)] = 937,
  [SMALL_STATE(88)] = 941,
  [SMALL_STATE(89)] = 945,
  [SMALL_STATE(90)] = 949,
  [SMALL_STATE(91)] = 953,
  [SMALL_STATE(92)] = 957,
  [SMALL_STATE(93)] = 961,
  [SMALL_STATE(94)] = 965,
  [SMALL_STATE(95)] = 969,
  [SMALL_STATE(96)] = 973,
  [SMALL_STATE(97)] = 977,
  [SMALL_STATE(98)] = 981,
  [SMALL_STATE(99)] = 985,
  [SMALL_STATE(100)] = 989,
  [SMALL_STATE(101)] = 993,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nidl_document_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nidl_document_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nidl_document_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nidl_document_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nidl_document_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nidl_document_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_host_function_declaration, 9, 0, 11),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opaque_declaration, 3, 0, 1),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_enum_declaration, 4, 0, 1),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_member, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_struct_declaration, 4, 0, 1),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_struct_declaration, 5, 0, 1),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_enum_declaration, 5, 0, 1),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_host_function_declaration, 7, 0, 9),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_declaration, 6, 0, 5),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_host_function_declaration, 8, 0, 10),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_type_identifier, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_type, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_builtin_type, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_enum_variant, 1, 0, 3),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nidl_struct_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nidl_struct_declaration_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nidl_enum_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nidl_enum_declaration_repeat1, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_type_argument_list, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_generic_type, 2, 0, 6),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_type_argument_list, 4, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_host_mode_keyword, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nidl_enum_declaration_repeat1, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_enum_variant, 4, 0, 8),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nidl_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nidl_parameter_list_repeat1, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nidl_type_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nidl_type_argument_list_repeat1, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_parameter, 3, 0, 4),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_policy, 5, 0, 7),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_field_declaration, 4, 0, 4),
  [158] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_abandon_policy_keyword, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_document, 4, 0, 1),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_parameter_list, 4, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_parameter_list, 3, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cancel_policy_keyword, 1, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_parameter_list, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fuel_clause, 2, 0, 2),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nidl_document, 5, 0, 1),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nexa_idl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_nidl_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "nexa_idl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
